### PR TITLE
New landing pages

### PR DESCRIPTION
**Pull request by idengager**
Crystals and gradient version. Tested on mobile (iOS, Android), iPad and desktops (Safari, Chrome, Firefox, non-retina). Some final thoughts/issues:
1. ~~should company logo be displayed as text or an image?~~
2. do we want to stick to the designs concerning the footer on desktops? Looks alright, but the code for it doesn't.
3. ~~the technology logos might not look great on retina screens.~~
4. make sure form data gets saved.

Kudos to @yakato for all the pair-programming and tips.

### CODE REVIEW

**Comment by imanel** [comment]
Looks nice - good job everyone :)

**Comment by yakato** [comment]
Retested on retina - works.

**Comment by tomash** [comment]
let's merge! :+1:

**Comment by imanel** [comment]
@yakato after yesterday's fixes everything is ready to push. Feel free to merge 😄

**Comment by yakato** [comment]
@imanel great, but I'm not authorized to merge

**Pull request merged**
